include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    argument_type_not_assignable: ignore
    sort_unnamed_constructors_first: ignore
