name: interviewer_quiz_flutter_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # H_ essential
  json_annotation: ^4.0.1
  path_provider: ^2.0.1
  freezed_annotation: ^0.14.2
  uuid: ^3.0.4
  logger: ^1.0.0
  # H_ get_it
  get_it: ^7.1.3
  injectable: ^1.4.0
  # H_ bloc
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  # H_ firebase
  firebase_core: ^1.1.1
  cloud_firestore: ^2.1.0
  # H_ recorder
  flutter_sound: ^8.1.1
  permission_handler: ^7.1.0
  # H_ route
  auto_route: ^2.2.0
  # H_ widget/presentation
  flutter_hooks: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_keyboard_visibility: ^5.0.2
  # scrollable_positioned_list: ^0.2.0-nullsafety.0
  scrollable_positioned_list:
    git:
      url: https://github.com/lvfen/flutter.widgets.git
      ref: shrinkWrapSupport
      path: packages/scrollable_positioned_list
  # H_ others
  dartz: ^0.10.0-nullsafety.2
  kt_dart: ^0.9.0
  tuple: ^2.0.0
  rxdart: ^0.27.0
  expression_language: ^1.0.0
  isolate: ^2.1.0
  path: ^1.8.0
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  # H_ essential
  json_serializable: ^4.1.1
  freezed: ^0.14.2
  # H_ get_it
  injectable_generator: ^1.4.0
  # H_ route
  auto_route_generator: ^2.1.0
  # H_ lint
  lint: ^1.5.3


flutter:
  uses-material-design: true

  assets:
     - assets/interviewer_list.json

  fonts:
    - family: NotoSansTC
      fonts:
        - asset: fonts/NotoSansTC-Thin.otf
          weight: 100
        - asset: fonts/NotoSansTC-Light.otf
          weight: 300
        - asset: fonts/NotoSansTC-Regular.otf
          weight: 400
        - asset: fonts/NotoSansTC-Medium.otf
          weight: 500
        - asset: fonts/NotoSansTC-Bold.otf
          weight: 700
        - asset: fonts/NotoSansTC-Black.otf
          weight: 900
